# version: '3.8'

services:
    lmw-web:
        build:
            context: ./
            dockerfile: Dockerfile
        image: lmw-web-image
        container_name: lmw-web-app
        restart: always
        working_dir: /var/www/

        volumes:
            - ./src:/var/www
            - ./config/.env:/var/www/.env
            - ./src/storage:/var/www/storage
            - /etc/ssl/wapresri/b.wapresri.go.id.key:/etc/nginx/ssl/server.key:ro
            - /etc/ssl/wapresri/combined_server_chain.crt:/etc/nginx/ssl/combined_server_chain.crt:ro
        ports:
            - "80:8080"
            - "443:8443"
        networks:
            - lmw-network
        depends_on:
            mysql:
                condition: service_healthy
            redis:
                condition: service_healthy
            minio:
                condition: service_started

        environment:
            APP_ENV: local
            APP_DEBUG: ${APP_DEBUG:-true}

    lmw-api:
        build:
            context: ./
            dockerfile: Dockerfile
        image: lmw-api-image
        container_name: lmw-api-app
        restart: always
        working_dir: /var/www/

        volumes:
            - ./src:/var/www
            - ./config/.env:/var/www/.env
        ports:
            - "8080:8080"
        networks:
            - lmw-network
        depends_on:
            mysql:
                condition: service_healthy
            redis:
                condition: service_healthy
            minio:
                condition: service_started
        environment:
            APP_ENV: local
            APP_DEBUG: ${APP_DEBUG:-true}
            IS_API_SERVER: 'true'

    lmw-scheduler:
        build:
            context: ./
            dockerfile: Dockerfile

        image: lmw-scheduler-image
        container_name: lmw-scheduler
        restart: always
        working_dir: /var/www/

        volumes:
            - ./src:/var/www
            - ./config/.env:/var/www/.env
            - ./config/supervisord-scheduler.conf:/etc/supervisor/conf.d/supervisord.conf

        command: /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf

        networks:
            - lmw-network
        depends_on:
            - mysql
            - redis

    mysql:
        image: 'mysql/mysql-server:8.0'
        container_name: lmw-db
        restart: always
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_EXTRA_OPTIONS: '${MYSQL_EXTRA_OPTIONS}'
        volumes:
            - 'lmw-mysql-data:/var/lib/mysql'
        networks:
            - lmw-network
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
            retries: 3
            timeout: 5s

    redis:
        image: 'redis:alpine'
        container_name: lmw-redis
        restart: always
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'lmw-redis-data:/data'
        networks:
            - lmw-network
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            retries: 3
            timeout: 5s

    mailpit:
        image: 'axllent/mailpit:latest'
        container_name: lmw-mailpit
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        networks:
            - lmw-network

    minio:
        image: 'minio/minio:latest'
        container_name: lmw-minio
        ports:
            - '0.0.0.0:${FORWARD_MINIO_PORT:-9000}:9000'
            - '0.0.0.0:${FORWARD_MINIO_CONSOLE_PORT:-8900}:8900'
        environment:
            MINIO_ROOT_USER: lmw
            MINIO_ROOT_PASSWORD: password
        volumes:
            - 'lmw-minio-data:/data'
        networks:
            - lmw-network
        command: 'minio server /data --console-address ":8900"'
        healthcheck:
            test: [ "CMD", "mc", "ready", "local" ]
            retries: 3
            timeout: 5s

networks:
    lmw-network:
        driver: bridge

volumes:
    lmw-mysql-data:
        driver: local
    lmw-redis-data:
        driver: local
    lmw-minio-data:
        driver: local
